---
title: Getting Started with R
format:
  rfortherestofus-slides-revealjs:
    menu: false
    progress: true
    slide-number: true
    show-slide-number: print
    center: true
    incremental: true
execute: 
  message: false
  warning: false
  cache: false
title-slide-attributes:
  data-background-image: assets/rru-hex-bg-gradient-dark.svg
  data-background-size: cover
---

# Welcome to Getting Started with R {.inverse}

# Install R {.inverse}

## Your Turn {.your-turn}

- [Download and install R](https://posit.co/download/rstudio-desktop/)
- Use any mathematical operators (+, -, /, and *) to create an expression and make sure it works as expected

# Install RStudio {.inverse}

## Your Turn {.your-turn}

- Download and install RStudio

# R Script Files {.inverse}

## Your Turn {.your-turn}

- Create and save an R script file
- Enter a mathematical expression on your R script file and run it

# RStudio Projects {.inverse}

## Your Turn {.your-turn}

- Download the course project

. . .

```{r eval = FALSE, echo = TRUE}
install.packages(pkgs = "usethis")
library(package = usethis)
use_course(url = "http://bit.ly/getting-started-with-r")
```

- Open the project and look at the files within it

# R Packages {.inverse}

## Your Turn {.your-turn}

- Working in the console, install the `tidyverse` package using the code `install.packages("tidyverse")`
- Check in the Packages tab on the bottom right panel to confirm that the `tidyverse` package has been installed successfully

# Import Data {.inverse}

## Your Turn {.your-turn}

- Add the line `library(tidyverse)` at the top of your R script file and run it to load the `tidyverse`
- Use the `read_csv()` function (not `read.csv()`) to import the `penguins.csv` file

# Objects and Functions {.inverse}

## Your Turn {.your-turn}

- Adapt your code from the last lesson so that it saves the data as an object called `penguins_data`

# Examine Data {.inverse}

- Examine data with one of three packages I suggest

## Your Turn {.your-turn}

# Import Data Again {.inverse}

## Your Turn {.your-turn}

- Reimport data

# Getting Help {.inverse}

## Your Turn {.your-turn}

# Wrapping Up {.inverse}

## Your Turn {.your-turn}